### 

@baseUrl = http://localhost:3001/api


### get all persons

GET {{baseUrl}}/persons HTTP/1.1


### get info

GET {{baseUrl}}/info HTTP/1.1


### get person by id

GET {{baseUrl}}/persons/69ea0ede115875815c6686c4 HTTP/1.1


### delete person by id

DELETE {{baseUrl}}/persons/69e8cddbdd8b5b74f144e79 HTTP/1.1


### create person

POST {{baseUrl}}/persons HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "number": "12345"
}


### update person

PUT {{baseUrl}}/persons/69ea0ede115875815c6686c4 HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "number": "98765"
}
