### 

@baseUrl = https://phonebook-backend-ufzo.onrender.com/api


### get all persons

GET {{baseUrl}}/persons HTTP/1.1


### get info

GET {{baseUrl}}/info HTTP/1.1


### get person by id

GET {{baseUrl}}/persons/2 HTTP/1.1


### delete person by id

DELETE {{baseUrl}}/persons/3 HTTP/1.1


### create person

POST {{baseUrl}}/persons HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "number": "12345"
}
